# Line length
line-length = 79
# Fixes violations if safe to do so
fix = true
# Group violations by containing file
output-format = "grouped"

# Taken from:
# https://docs.astral.sh/ruff/linter/#rule-selection
# "some of the most popular rules (without being too pedantic)":
[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
