name: ruff check --no-fix
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1.1.0
        with:
          args: 'check --no-fix'
